{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbupgrade-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbupgrade-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "dbupgrade-operator.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbupgrade-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbupgrade-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "dbupgrade-operator.selectorLabels" . | nindent 4 }}
{{- end }}
