{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dbupgrade-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbupgrade-operator.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- if .Values.serviceAccount.annotations }}
  {{- $annotations = merge $annotations .Values.serviceAccount.annotations }}
  {{- end }}
  {{- if and .Values.aws.enabled .Values.aws.serviceAccountAnnotations }}
  {{- $annotations = merge $annotations .Values.aws.serviceAccountAnnotations }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
