{{- if .Values.webhook.enabled }}
{{- if .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "dbupgrade-operator.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbupgrade-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "dbupgrade-operator.fullname" . }}-webhook-cert
  dnsNames:
    - {{ include "dbupgrade-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "dbupgrade-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.webhook.certManager.issuerRef.name }}
    kind: {{ .Values.webhook.certManager.issuerRef.kind }}
---
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "dbupgrade-operator.fullname" . }}-validating
  labels:
    {{- include "dbupgrade-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "dbupgrade-operator.fullname" . }}-webhook-cert
  {{- end }}
webhooks:
  - name: vdbupgrade.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "dbupgrade-operator.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-dbupgrade-subbug-learning-v1alpha1-dbupgrade
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - dbupgrade.subbug.learning
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - dbupgrades
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
{{- end }}
