# Kind cluster configuration for E2E tests
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dbupgrade-e2e
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    # Expose host ports for debugging
    extraPortMappings:
      - containerPort: 30432
        hostPort: 30432
        protocol: TCP
